# utility
/null:
    type: 'null'
    path: None
    icon: tag
    label: Unresolved
    description:
        - Unresolved
    option:
        enable: False
#
/geometry:
    type: group
    path: <..key>
    icon: tag
    label: Geometry
    description:
        - Geometry
    option:
        enable: True
#
/geometry/abc:
    type: method
    path: <..key>
    icon: tag
    label: Abc
    description:
        - Geometry-abc
    option:
        enable: True
#
/geometry/usd:
    type: method
    path: <..key>
    icon: tag
    label: Usd
    description:
        - Geometry-usd
    option:
        enable: True
#
