# project
project:
    checker: []
# asset
asset:
    checker:
        # utility
        - /utl/reference_custom
        - /utl/namespace_custom
        - /utl/node_custom
        - /utl/shape_custom
        - /utl/file_reference_custom
        - /utl/image_reference_custom
        - /utl/display_layer_custom
# shot
shot:
    checker:
        - /utl/reference_custom
        - /utl/namespace_custom
        - /utl/node_custom
        - /utl/file_reference_custom
        - /utl/image_reference_custom
        - /ett/shot_frame_range_custom
# asset-model / mdl
asset/mod:
    checker:
        # branch
        - <asset.checker>
        # step
        - /utl/group_custom
        - /ett/asset_group_custom
        - /ett/asset_reference_custom
        - /mod/geometry_custom
        - /mod/mesh_custom
        - /mod/mesh_topology_custom
        - /mod/mesh_manifold_custom
        - /mod/mesh_map_custom
    exporter:
        work:
            - /geometry/alembic
            - /geometry/usd
            - /look/ass
        publish:
            - /geometry/alembic
            - /geometry/usd
            - /look/ass
# asset-rig
asset/rig:
    checker:
        # branch
        - <asset.checker>
        # step
        - /ett/asset_reference_custom
        - /rig/skin_custom
        - /rig/control_custom
# asset-groom
asset/grm:
    checker:
        # branch
        - <asset.checker>
        # step
        - /ett/asset_reference_custom
        - /grm/xgen_palette_custom
        - /grm/xgen_description_custom
        - /grm/xgen_grow_mesh_custom
# asset-surface / look-dev
asset/srf:
    checker:
        # branch
        - <asset.checker>
        # model
        # - <asset/mod.checker>
        # groom
        # - <asset/grm.checker>
        - /srf/texture_custom
        - /srf/material_custom
    exporter:
        work:
            - /surface/geometry_to_work
            - /surface/texture_to_work
            - /surface/look_to_work
        publish:
            - /surface/geometry
            - /surface/texture
            - /surface/look
            - /surface/scene
# shot-layout / rlo
shot/rlo:
    checker:
        # branch
        - <shot.checker>
        # layout / animation
        - /utl/animation_layer_custom
        - /ani/constrain_custom
        - /ani/display_layer_custom
        - /ani/temporary_node_custom
# shot-animation / ani
shot/ani:
    checker:
        # branch
        - <shot.checker>
        # layout / animation
        - /utl/animation_layer_custom
        - /ani/constrain_custom
        - /ani/display_layer_custom
        - /ani/temporary_node_custom