# utility
/utl/materialx_custom:
    # gui-icon
    icon: None
    # gui-label
    label: Materialx(s)
    # gui-descriptions
    descriptions:
        - Texture-path is Non-exists:
            notes:
                - '“.mtlx”文件中关联的贴图文件缺失，需要Surface环节找到丢失的贴图并重新发布'
            repair:
                description: Find Lost-texture-path and Republish
                note: None
            ignore:
                enable: True
# shot
/sot/alembic_custom:
    # gui-icon
    icon: None
    # gui-label
    label: Alembic(s)
    # gui-descriptions
    descriptions:
        - Materialx "path" is Not found in Alembic:
            notes:
                - '“.mtlx”文件中的“path”在“.abc”文件中“path”中无法找到'
            repair:
                description: Find Lost-texture-path and Republish
                note: None
            ignore:
                enable: True

        - Alembic "path" is Not found in Materialx:
              notes:
                  - '“.abc”文件中的“path”在“.mtlx”文件中“path”中无法找到'
              repair:
                  description: Find Lost-texture-path and Republish
                  note: None
              ignore:
                  enable: True